apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: blargh2
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: true
    jsonData:
      esVersion: 7.10.0
      timeField: '@timestamp'
      tlsSkipVerify: false
      maxConcurrentShardRequests: 5

