{
 "title": "SAR",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod_id",
    "query": "{\"find\": \"terms\", \"field\": \"host.name.keyword\"}"
   },
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"host.name.keyword\"}"
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "nic",
    "query": "{\"find\": \"terms\", \"field\": \"net-dev.iface.keyword\",\"query\":\"sam* OR br*\"}"
   },
   {
    "name": "disk",
    "query": "{\"find\": \"terms\", \"field\": \"disk.disk-device.keyword\"}"
   },
   {
    "name": "cpu",
    "query": "{\"find\": \"terms\", \"field\": \"cpu-load-all.cpu.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "commit {{term host.name.keyword}}",
     "bucketAggs": [
      {
       "field": "host.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "memory.commit", "id": "1", "type": "avg" }
     ],
     "query": "host.name.keyword: ${hostname:lucene}",
     "timeField": "@timestamp"
    },
    {
     "alias": "used  {{term host.name.keyword}}",
     "bucketAggs": [
      {
       "field": "host.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "memory.memused", "id": "1", "type": "avg" }
     ],
     "query": "host.name.keyword: ${hostname:lucene}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "rx {{term net-dev.iface.keyword}}  {{term host.name.keyword}}",
     "bucketAggs": [
      {
       "field": "net-dev.iface.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "host.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "net-dev.rxkB",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "net-dev.iface.keyword:${nic:lucene} AND host.name.keyword:${hostname:lucene} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "tx {{term net-dev.iface.keyword}}  {{term host.name.keyword}}",
     "bucketAggs": [
      {
       "field": "net-dev.iface.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "host.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "net-dev.txkB",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "net-dev.iface.keyword:${nic:lucene} AND host.name.keyword:${hostname:lucene} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network error",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 23, "x": 0, "y": 56 },
   "targets": [
    {
     "alias": "drop {{term net-edev.iface.keyword}}  {{term host.name.keyword}}",
     "bucketAggs": [
      {
       "field": "net-edev.iface.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "host.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "net-edev.rxdrop",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "net-edev.iface.keyword:${nic:lucene} AND host.name.keyword:${hostname:lucene} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "disk",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 23, "x": 0, "y": 80 },
   "targets": [
    {
     "alias": "await {{term disk.disk-device.keyword}}  {{term host.name.keyword}}",
     "bucketAggs": [
      {
       "field": "disk.disk-device.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "host.name.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "disk.await",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "disk.disk-device.keyword:${disk:lucene} AND host.name.keyword:${hostname:lucene} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 23, "x": 0, "y": 104 },
   "targets": [
    {
     "alias": "{{term cpu-load-all.cpu.keyword}}  {{term host.name.keyword}}",
     "bucketAggs": [
      {
       "field": "cpu-load-all.cpu.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "host.name.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "cpu-load-all.idle",
       "hide": false,
       "id": "1",
       "settings": { "script": "100-_value" },
       "type": "avg"
      }
     ],
     "query": "cpu-load-all.cpu.keyword:${cpu:lucene} AND host.name.keyword:${hostname:lucene} ",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}