version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$VERSION
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    environment:
      ES_JAVA_OPTS: "-Xms4096m -Xmx4096m"
      discovery.type: "single-node"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9200/_cluster/health|grep -Eq 'green|yellow'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  setup: 
    image: curlimages/curl
    command: >
      -X PUT "elasticsearch:9200/blargh2/?pretty" -H 'Content-Type: application/json' -d' { "mappings": { "dynamic_templates": [ { "float": { "match_mapping_type": "long", "mapping": { "type": "float" } } } ] } }'
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:$VERSION
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/usr/share/kibana/config"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -I http://localhost:5601/status",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  logstash:
    image: docker.elastic.co/logstash/logstash:$VERSION
    ports:
      - 5044:5044
    volumes:
      - type: bind
        source: ./logstash
        target: /usr/share/logstash/config/
    depends_on:
      kibana:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9600|grep -q green",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  filebeat:
    image: docker.elastic.co/beats/filebeat:$VERSION
    mem_limit: 1G
    volumes:
      - type: bind
        source: $FILEBEATLOCALFILE
        target: /usr/share/filebeat/input
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: volume
        source: filebeat_data
        target: /usr/share/
    depends_on:
      logstash:
        condition: service_healthy

  grafana:
    image: grafana/grafana-oss:8.3.4
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: grafana/datasource.yml
        target: /etc/grafana/provisioning/datasources/datasource.yml
      - type: bind
        source: grafana/dashboard.yml
        target: /etc/grafana/provisioning/dashboards/dashboard.yml
      - type: bind
        source: grafana/dashboard.json
        target: /etc/dashboards/dashboard.json
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    depends_on:
      kibana:
        condition: service_healthy

  inotify:
    image: inotify:latest
    environment:
      TZ: "Japan"
      SPLIT: false
    volumes:
      - type: bind
        source: $FILEBEATLOCALFILE
        target: /input
    depends_on:
      kibana:
        condition: service_healthy


volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  filebeat_data:
    driver: local
  grafana-storage:
    driver: local
