version: '2'

services:
  grafaba:
    image: grafana/grafana-oss
    ports:
      - '3001:3000'
    volumes:
      - type: bind
        source: grafana/datasource.yml 
        target: /etc/grafana/provisioning/datasources/datasource.yml
      - type: bind
        source: grafana/dashboard.yml 
        target: /etc/grafana/provisioning/dashboards/dashboard.yml
      - type: bind
        source: grafana/dashboard.json
        target: /etc/dashboards/dashboard.json
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
volumes:
  grafana-storage:
